(define (problem seat-customers) 
	(:domain restaurant-managing)
	(:objects group1with4 group2 group3 group4
				group5 group6 group7with4 group8 group9 group10with4 - group
			table1 table2 table3 table4 table5 table6 table7
					table8 - table
			Joe Mojo Alex - staffmember)
	(:init 	(= (people-count group1with4) 4)
			(= (people-count group2) 2)
			(= (people-count group3) 2)
			(= (people-count group4) 2) 
			(= (people-count group5) 2) 
			(= (people-count group6) 2)
			(= (people-count group7with4) 4) 
			(= (people-count group8) 2)
			(= (people-count group9) 2) 
			(= (people-count group10with4) 4)
		
			(= (table-capacity table1) 2)		
			(= (table-capacity table2) 2)
			(= (table-capacity table3) 2)
			(= (table-capacity table4) 2)
			(= (table-capacity table5) 2)
			(= (table-capacity table6) 2)
			(= (table-capacity table7) 2)
			(= (table-capacity table8) 2)
			
			; group 4 is already seated on table 3, and has ordered
			(seated group4 table3)
			(ordered group4 table3)
			(not-served group4)
			
			; group 6 is already seated on table8, and has been already served
			(seated group6 table8) 
			(served group6)
			
			(waiting-table group1with4)
			(waiting-table group2)
			(waiting-table group3)
			(waiting-table group5)
			(waiting-table group7with4)
			(waiting-table group8)
			(waiting-table group9)
			(waiting-table group10with4)
		
			(not-served group1with4)
			(not-served group2)
			(not-served group3)
			(not-served group5)
			(not-served group7with4)
			(not-served group8)
			(not-served group9)
			(not-served group10with4)
			
			(table-available table1)
			(table-available table2)
			(table-available table4)
			(table-available table5)
			(table-available table6)
			(table-available table7)
			
			(separate table1) 
			(separate table2)
			(separate table3) 
			(separate table4) 
			(separate table5)
			(separate table6) 
			(separate table7)
			(separate table8) 
		
			(member-available Joe)
			(member-available Mojo)
			(member-available Alex)
			)
	(:goal (and (served group1)
				(served group2)
				(served group3)
				(served group4)
				(served group5)
				(served group6)
				(served group7)
				(served group8)
				(served group9)
				(served group10)))
	(:metric minimize (total-time))
)